spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/books
    username: postgres
    password: p@ssw0rd
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    com.onevizion: trace
    web: debug